### ISSUE TITLE
[Question] SVT-AV1 and Av1an updates

### ISSUE THREAD

**Issue by 413Michele** [n00mkrad/nmkoder#36]
It has been some time since the last nmkoder release, and in the meantime there were important improvements in SVT-AV1, both in speed and features added. An example is better film grain generation and the option to disable source denoising. Av1an too, even without a number release, has had a lot of changes and bugfixes, which it offers as compiled builds from master.

Is a new nmkoder release that takes advantages of these new versions planned?

In any case, thank you for your work! Your GUI makes testing and encoding with AV1 really nice and easy 👍

**Comment by tyeeman** [comment]
Looks like there is a "bin" folder. Can't we just download and copy to the required folder in there?

**Comment by jll5** [comment]
> Looks like there is a "bin" folder. Can't we just download and copy to the required folder in there?

You can update SVT-AV1 binaries yourself by simply copying updated exe file over the preexisting one in "bin" folder, but any improvements that were added recently (like disabling source denoising) would not just appear in nmkoder. You could force that option by adding it to advanced arguments, but I am not sure if nmkoder would override it because the denoising checkbox next to grain synthesis would still remain grayed-out. And you would have to do this manually for every new feature you want to use.

I can only assume that av1an would be even more difficult to manually update and setup to work.

**Comment by chs4000** [comment]
In theory yes you can update the binaries underneath nmkoder, and that works up to a point, but a few things have changed in ffmpeg, SVT-AV1 (&AOM -- tho not sure on this). Some of the changes that have occurred in ffmpeg & SVT-AV1 do not play nicely with the nmkoder 1.10.0 from five months ago. I like this app a lot and the author is a man I respect a lot so I'll just patiently wait for a new nmkoder release to be compiled before I launch back into my AV1 experiments.

**Comment by n00mkrad** [comment]
Will include up to date binaries in the next update. Expect it somewhat soon

**Comment by 413Michele** [comment]
Sorry to ping but some time has passed now, is there any chance of an update or is it better to look elsewhere?

**Comment by Werve** [comment]
After several attempts I think I figured out how to get the encoding to work with the latest version of av1an and svt-av1 0.9.0 (I think even higher) and VMAF target option.

Nmkoder currently invokes av1an with the following problematic arguments:

- `--path <path>` which can be omitted or used as relative path instead of absolute path to avoid cases of path being too long or containing characters that create errors in the vapoursynth script ( `Traceback (most recent call last):
          File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
          File "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate` ) 

- When using the VMAF target option apparently you need to remove in the `-v` argument for the svt-av1 encoder `-crf <number>` otherwise it just reports that it is not in the range 1-63

**Comment by DesertCookie** [comment]
Any updates on this?

**Comment by chs4000** [comment]
I think he wants to focus on his frame interpolation software and just
doesn't want to be bothered with binaries for nmkoder. I'm saddened by this
but it's his prerogative how he sets his priorities. I'm not smart enough
to compile code, so I just have to look elsewhere now. Thank you for the
good times though, nmk.
