### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by neoOpus** [n00mkrad/nmkoder#6]
On the the shell window 

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core\src\settings.rs:961:21

**Comment by neoOpus** [comment]
INFO [av1an_core::settings] temporary directory: C:\Users\neoop\Downloads\Nmkoder\data\av1anTemp\1640236162720
Scene detection
INFO [av1an_core::settings] scenecut: found 7 scene(s) [with extra_splits(240 frames): 306]
00:07:02 [#####################################################################] 100%  72715/72715 (171.96 fps, eta 0s)
Queue 306 Workers 4 Passes 1
Params: --preset 5 --crf 20 --keyint 480 --lp 2 --film-grain 0 --tile-rows 1 --tile-columns 0
[Worker 1] Svt[info]: -------------------------------------------
00:00:03 [------------------------------------------------------------------------------]   0%  0/72715 (0 fps, eta 0s)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1094995529: Invalid data found when processing input)', av1an-core\src\broker.rs:250:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Worker 1] Svt[info]: -------------------------------------------
[Worker 2] Svt[info]: -------------------------------------------
[Worker 1] Svt[info]: -------------------------------------------
[Worker 2] Svt[info]: -------------------------------------------
[Worker 1] Svt[info]: -------------------------------------------
[Worker 2] Svt[info]: -------------------------------------------
[Worker 3] Svt[info]: -------------------------------------------
[Worker 4] Svt[info]: -------------------------------------------
04:28:37 [###############>--------------------------]  37%  26545/72715 (1.65 fps, eta 8h, 1247.6 Kbps, est. 180.25MiB)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1094995529: Invalid data found when processing input)', av1an-core\src\broker.rs:250:70
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core\src\settings.rs:994:21

[process exited with code 101]

**Comment by n00mkrad** [comment]
Seems to be a problem with your input video. Did you do lossless cutting? av1an doesn't like that.

**Comment by neoOpus** [comment]
Nope, but I will try with other videos to see if the problem persists, stay tuned

**Comment by neoOpus** [comment]
What about this Error instance 1: Source Width must be at least 64 ?

**Comment by n00mkrad** [comment]
Piping error. Either the input video is broken or the encoder is misconfigured

**Comment by neoOpus** [comment]
Oddly the errors disappear when I set the thread per worker to 1 and amount of worker to 2... so I guess there are some bugs in the encoder... but I am still trying to figure out via the settings changes what causes this... here is the specs of the laptop I am using

General specifications 
Operating system 
Windows 11 Home 64-bit Version: 22000.376 

Microprocessor 
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 

System memory 
64 GB 

Memory slot 1 
32GB A-DATA Technology 3200MHz 
Memory slot 2 
32GB A-DATA Technology 3200MHz

Video 
Graphic device 1 
Intel(R) Iris(R) Xe Graphics 

Version 
30.0.101.1191 (2021-12-03) 

Graphic device 2 
NVIDIA GeForce MX450 

Version 
30.0.14.9729 (2021-12-15)
